version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    ports:
      - "3000:3000"
    depends_on:
      - mysql_5.7

  mysql_5.7:
    image: mysql:5.7
    env_file: .env
    environment:
      - MYSQL_ROOT_USER=$MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports: 
      - 32769:3306
    restart: unless-stopped
  # mysql_5.7:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: mysql_5.7
  #   environment:
  #     - MYSQL_ROOT_USER=root
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=SalaryChange
  #   ports: 
  #     - 32769:3306
  #   restart: unless-stopped
  
  # mongo_db:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   restart: unless-stopped